import pickle

# دیکشنری که می‌خواهید ذخیره کنید
courses = {
    "Data Manipulation in Python - Master Python, NumPy, and Pandas": "https://t.me/Course_Number_1/961",
    "Data Science On Your First Day with Python": "https://t.me/Course_Number_1/959",
    "Learn Enough Python to be Dangerous A Tutorial Introduction to Programming with Python": "https://t.me/Course_Number_1/265",
    "Python for Data Science and Machine Learning Zero to Hero": "https://t.me/Course_Number_1/756",
    "Python for Data Visualization - A Beginner's Guide": "https://t.me/Course_Number_1/348",
    "Python for Deep Learning": "https://t.me/Course_Number_1/488",
    "Python for OOP - The A to Z OOP Python Programming Course": "https://t.me/Course_Number_1/451",
    "Python GUI Development with Tkinter - Build Pro Desktop Apps!": "https://t.me/Course_Number_1/407",
    "The Complete Python Programming Course Beginner to Advanced": "https://t.me/Course_Number_1/104",
    "Job-Ready SQL in an Afternoon": "https://t.me/Course_Number_1/1081",
    "SQL 101 Databases for Beginners": "https://t.me/Course_Number_1/1139",
    "Learn How to Learn Coding Faster Object-Oriented Programming in Python": "https://t.me/Course_Number_1/1151",
    "The No-Code Data Science Masterclass for Business Analysts & Executives": "https://t.me/Course_Number_1/1170",
    "Concurrent and Parallel Programming in Python": "https://t.me/Course_Number_1/1186",
    "Computer Vision 101 Let's Build a Face Swapper in Python": "https://t.me/Course_Number_1/1218",
    "Unlock your Creative Potential with AI ChatGPT for Content Creator": "https://t.me/Course_Number_1/1227",
    "Kick Butt in Coding Interviews Data Structures in Python": "https://t.me/Course_Number_1/1240",
    "Craft your Attention-Grabbing Resumé for a Career Change into Data, Tech, and AI": "https://t.me/Course_Number_1/1254",
    "Coding 101 Python for Beginners": "https://t.me/Course_Number_1/1267",
    "Python for Software Engineering Bootcamp": "https://t.me/Course_Number_1/1285",
    "Artificial Intelligence for Beginners How ChatGPT Works": "https://t.me/Course_Number_1/1482",
    "Artificial Intelligence for Beginners Tools to Learn Machine Learning": "https://t.me/Course_Number_1/1488",
    "Data Science 101 Python Data Visualization for Beginners": "https://t.me/Course_Number_1/1501",
    "Data Science and Machine Learning with Python": "https://t.me/Course_Number_1/1510",
    "Data Science Prerequisites - Numpy, Matplotlib, and Pandas in Python": "https://t.me/Course_Number_1/1547",
    "Python Machine Learning Bootcamp": "https://t.me/Course_Number_1/1596",
    "Advanced Microsoft Excel": "https://t.me/Course_Number_1/1707",
    "AI Applications for Business Success": "https://t.me/Course_Number_1/1803",
    "Convolutional Neural Networks with TensorFlow in Python": "https://t.me/Course_Number_1/1837",
    "Introduction to Jupyter": "https://t.me/Course_Number_1/1970",
    "Git and GitHub": "https://t.me/Course_Number_1/1991",
    "Mathematics": "https://t.me/Course_Number_1/2008",
    "Practical GitHub Actions": "https://t.me/Course_Number_1/2040",
    "Practical GitHub Project Management and Collaboration": "https://t.me/Course_Number_1/2058",
    "Practical GitHub Copilot": "https://t.me/Course_Number_1/2079",
    "Practical GitHub Code Search": "https://t.me/Course_Number_1/2100",
    "Practical Python Learn Python Basics Step by Step - Python 3": "https://t.me/Course_Number_1/2117",
    "Python in Practice - 15 Projects to Master Python": "https://t.me/Course_Number_1/2178",
    "Complete Python Course with 10 Real-World Projects": "https://t.me/Course_Number_1/2411",
    "Become a Expert In Java Go Beginner To Advance": "https://t.me/Course_Number_1/2689",
    "A Complete Guide to Engineering Equation Solver EES 2021-2": "https://t.me/Course_Number_1/2815",
    "Learning MATLAB": "https://t.me/Course_Number_1/2847",
    "MATLAB Essential Training": "https://t.me/Course_Number_1/2881",
    "Python Environments and Best Practices": "https://t.me/Course_Number_1/2931",
    "Python Programmer Bootcamp": "https://t.me/Course_Number_1/2936",
    "Web Scraping and API Fundamentals in Python": "https://t.me/Course_Number_1/3290",
    "Python for Finance": "https://t.me/Course_Number_1/3430",
    "PyCharm IDE for Beginners The Complete Guide": "https://t.me/Course_Number_1/3721",
    "Additive Manufacturing - Metal 3D Printing": "https://t.me/Course_Number_1/3744",
    "70+ Basic Electrical, Electronic & Logic Symbols Explanation": "https://t.me/Course_Number_1/3796",
    "Projects in Django _ Learn Django Building Projects": "https://t.me/Course_Number_1/3816",
    "R Programming for Beginners": "https://t.me/Course_Number_1/3879",
    "Learn MATLAB": "https://t.me/Course_Number_1/3937",
    "MATLAB and Octave in Jupyter Notebook": "https://t.me/Course_Number_1/4023",
    "ALGORITHMIC TRADING WITH MATLAB AND WFATOOLBOX": "https://t.me/Course_Number_1/4060",
    "Bioinformatics with Python": "https://t.me/Course_Number_1/4085",
    "DNA Hacking with Swift 4 Xcode 9": "https://t.me/Course_Number_1/4142",
    "12 Myths About Data Science and AI": "https://t.me/Course_Number_1/4157",
    "Statistics": "https://t.me/Course_Number_1/4216",
    "Probability": "https://t.me/Course_Number_1/4384",
    "SOLIDWORKS - Advanced Filleting Techniques": "https://t.me/Course_Number_1/4503",
    "SOLIDWORKS - Advanced Mates": "https://t.me/Course_Number_1/4544",
    "SOLIDWORKS - Creating Simplified General Arrangements": "https://t.me/Course_Number_1/4580",
    "SOLIDWORKS - Design Communication Documentation - Consumer Products": "https://t.me/Course_Number_1/4611",
    "SOLIDWORKS - Drawings": "https://t.me/Course_Number_1/4640",
    "SOLIDWORKS - File Management": "https://t.me/Course_Number_1/4711",
    "SOLIDWORKS - Layout Based Assembly Modeling": "https://t.me/Course_Number_1/4750",
    "Ansys Fluent Class#1": "https://t.me/Course_Number_1/4791",
    "Ansys Fluent Class#2 Let's do more practice&SettingUpPhysics": "https://t.me/Course_Number_1/4985",
    "Ansys Fluent Class#3": "https://t.me/Course_Number_1/4811",
    "Ansys Fluent Class#4 Let's do more practice&Focus the Solver": "https://t.me/Course_Number_1/4826",
    "Ansys Fluent Class#5": "https://t.me/Course_Number_1/4840",
    "Ansys Fluent Class#6 Let's do more practice&Focus Turbulence": "https://t.me/Course_Number_1/5003",
    "Advanced CSS + JavaScript": "https://t.me/Course_Number_1/4873",
    "Intro to Python": "https://t.me/Course_Number_1/5025",
    "Intro to React.js": "https://t.me/Course_Number_1/5188",
    "Creative Coding​": "https://t.me/Course_Number_1/5279",
    "4 things you might not know about chrome devtools egghead‍": "https://t.me/Course_Number_1/5400",
    "introduction to the python 3 programming language‍": "https://t.me/Course_Number_1/5409",
    "Foundation HTML, CSS + Javascript​": "https://t.me/Course_Number_1/5438",
    "WordPress": "https://t.me/Course_Number_1/5692",
    "Python for the Web": "https://t.me/Course_Number_1/6179",
    "Aging _ lecturio": "https://t.me/Course_Number_1/6243",
    "12 Cranial Nerves and Their Functions _ lecturio": "https://t.me/Course_Number_1/6258",
    "Auditory System and Vestibular System _ lecturio": "https://t.me/Course_Number_1/6273",
    "Autonomic Nervous System (ANS) _ lecturio": "https://t.me/Course_Number_1/6285",
    "Basal Ganglia _ lecturio": "https://t.me/Course_Number_1/6290",
    "Brain Stem _ lecturio": "https://t.me/Course_Number_1/6295",
    "Cerebellum _ lecturio": "https://t.me/Course_Number_1/6308",
    "Cerebral Cortex _ lecturio": "https://t.me/Course_Number_1/6312",
    "Diencephalon _ lecturio": "https://t.me/Course_Number_1/6320",
    "Dural Venous Sinuses _ lecturio": "https://t.me/Course_Number_1/6326",
    "Limbic System _ lecturio": "https://t.me/Course_Number_1/6330",
    "Meninges _ lecturio": "https://t.me/Course_Number_1/6334",
    "Spinal Cord _ lecturio": "https://t.me/Course_Number_1/6339",
    "Ventricular System _ lecturio": "https://t.me/Course_Number_1/6349",
    "Visual Pathways _ lecturio": "https://t.me/Course_Number_1/6353",
    "Abdomen_ lecturio": "https://t.me/Course_Number_1/6360",
    "Abdominal Wall_ lecturio": "https://t.me/Course_Number_1/6375",
    "Head and Neck Anatomy _ lecturio": "https://t.me/Course_Number_1/6385",
    "Lower Limb Anatomy _ lecturio": "https://t.me/Course_Number_1/6408",
    "Pelvis _ lecturio": "https://t.me/Course_Number_1/6419",
    "Thoracic Viscera _ lecturio": "https://t.me/Course_Number_1/6427",
    "Upper Limb Anatomy _ lecturio": "https://t.me/Course_Number_1/6433",
    "Microbiology - Introduction _ lecturio": "https://t.me/Course_Number_1/6444",
    "Fungi _ lecturio": "https://t.me/Course_Number_1/6490",
    "TTC - The Learning Brain": "https://t.me/Course_Number_1/6513",
    "Bacteria _ lecturio": "https://t.me/Course_Number_1/6539",
    "Viruses _ lecturio": "https://t.me/Course_Number_1/6605",
    "Parasites _ lecturio": "https://t.me/Course_Number_1/6661",
    "Prions _ lecturio": "https://t.me/Course_Number_1/6686",
    "Microbiology _ educator": "https://t.me/Course_Number_1/6695",
    "Molecular Biology _ educator": "https://t.me/Course_Number_1/6743",
    "Biochemistry Masterclass _ Udemy": "https://t.me/Course_Number_1/6766",
    "TTC human body": "https://t.me/Course_Number_1/6779",
    "Web Development with HTML and CSS for Beginners _ udemy": "https://t.me/Course_Number_1/6815",
    "MATLAB Simulink - Simulink Course for Electrical Engineering 2024-3": "https://t.me/Course_Number_1/6832",
    "Learn to Code Beginners Python Programming 2024-3": "https://t.me/Course_Number_1/7263",
    "Introduction to MATLAB_TechPetraPro_Skillshare": "https://t.me/Course_Number_1/7494",
    "GitHub Fundamentals Bootcamp _ oreilly": "https://t.me/Course_Number_1/7522",
    "AutoCAD Electrical Essential Training _ LinkedIn": "https://t.me/Course_Number_1/7528",
    "Medical Biochemistry - Carbohydrate Metabolism Simplified": "https://t.me/Course_Number_1/7652",
    "Sketchy Internal Medicine": "https://t.me/Course_Number_1/7664",
    "De Novo Proteomics Data Analysis for Bioinformatics Research": "https://t.me/Course_Number_1/7776",
    "Innovating with Biomathematics": "https://t.me/Course_Number_1/7823",
    "Web Dev Fundamentals _ AlgoExpert": "https://t.me/Course_Number_1/7868",
    "JavaScript Crash Course _ AlgoExpert": "https://t.me/Course_Number_1/7877",
    "HTML Crash Course _ AlgoExpert": "https://t.me/Course_Number_1/7905",
    "CSS Crash Course _ AlgoExpert": "https://t.me/Course_Number_1/7915",
    "25 Frontend Interview Questions _ AlgoExpert": "https://t.me/Course_Number_1/7936",
    "150 Coding Interview Questions _ AlgoExpert": "https://t.me/Course_Number_1/7962",
    "egghead a journey with vue router": "https://t.me/Course_Number_1/8093",
    "egghead a to z in fp beyond the basics of functional programming f7ff": "https://t.me/Course_Number_1/8104",
    "egghead abstract syntax trees 3582efe5": "https://t.me/Course_Number_1/8114",
    "egghead accessibility tips tricks 49286904": "https://t.me/Course_Number_1/8117",
    "egghead accessible cross browser css form styling 7297": "https://t.me/Course_Number_1/8123",
    "Visual Design + Branding": "https://t.me/Course_Number_1/8270",
    "The Great Courses_ English Grammar Boot Camp": "https://t.me/Course_Number_1/8800",
    "SOLIDWORKS Simulation for Finite Element Analysis _ LinkedIn": "https://t.me/Course_Number_1/8852",
    "Animal Coordination and Control – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/8888",
    "Animal Coordination and Control – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/8895",
    "Animal Coordination and Control – Edexcel GCSE (1SC0)_ Combined Science (Foundation Tier) - Dr Matthew Ivory": "https://t.me/Course_Number_1/8904",
    "Animal Coordination and Control – Edexcel GCSE (1SC0)_ Combined Science (Higher Tier) - Dr Matthew Ivory": "https://t.me/Course_Number_1/8911",
    "Animal Exchange and Transport – (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/8920",
    "Animal Exchange and Transport – (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/8941",
    "Animal Exchange and Transport – (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/8962",
    "Animal Research - Dr Chris Willmott": "https://t.me/Course_Number_1/8981",
    "Astrobiology - Prof. Ian Crawford": "https://t.me/Course_Number_1/8992",
    "Brain Imaging - Prof. Karl Friston": "https://t.me/Course_Number_1/9009",
    "Cell Biology - Dr Matthew Ivory": "https://t.me/Course_Number_1/9018",
    "Cellular Division - Dr Matthew Ivory": "https://t.me/Course_Number_1/9027",
    "Communicable Disease - Dr Matthew Ivory": "https://t.me/Course_Number_1/9036",
    "DNA Damage and Repair - Prof. Karl Haushalter": "https://t.me/Course_Number_1/9047",
    "DNA Structure and Replication - Prof. Richard Bowater": "https://t.me/Course_Number_1/9058",
    "Drug Discovery and Development - Dr Matthew Ivory": "https://t.me/Course_Number_1/9071",
    "Ecosystems – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9082",
    "Ecosystems – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9101",
    "Ecosystems – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9122",
    "Enzyme Biology - Dr Matthew Ivory": "https://t.me/Course_Number_1/9133",
    "Ethics of Organ Transplantation - Dr Gregory Moorlock": "https://t.me/Course_Number_1/9142",
    "Eukaryotic Cell Biology - Prof. Jake Baum": "https://t.me/Course_Number_1/9153",
    "Evolution and Ecology - Prof. Adam Hart": "https://t.me/Course_Number_1/9164",
    "Fighting Disease – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9179",
    "Fighting Disease – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9186",
    "Fighting Disease – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9195",
    "Food Science – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9202",
    "Food Science – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9207",
    "Gas Exchange - Dr Helen Wallace": "https://t.me/Course_Number_1/9212",
    "Genetic Modification – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9217",
    "Genetic Modification – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9224",
    "Genetic Modification – Edexcel GCSE (1SC0)_ Combined Science (Foundation Tier) - Dr Matthew Ivory": "https://t.me/Course_Number_1/9231",
    "Genetic Modification – Edexcel GCSE (1SC0)_ Combined Science (Higher Tier) - Dr Matthew Ivory": "https://t.me/Course_Number_1/9236",
    "Genetic Variation - Dr Matthew Ivory": "https://t.me/Course_Number_1/9246",
    "Genetics – (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9275",
    "Genetics – (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9288",
    "Homeostasis – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9299",
    "Homeostasis – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9308",
    "Homeostasis – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9317",
    "Human Evolution - Prof. Matthew Cobb": "https://t.me/Course_Number_1/9324",
    "Human Health and Disease – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9333",
    "Human Health and Disease – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9342",
    "Human Health and Disease – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9353",
    "Human Immune System - Dr Matthew Ivory": "https://t.me/Course_Number_1/9364",
    "Human Organisation – AQA (8461) - Dr Nicola Aberdein": "https://t.me/Course_Number_1/9375",
    "Material Cycles – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9390",
    "Material Cycles – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9397",
    "Material Cycles – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9404",
    "Maths for Biology - Dr Chris Willmott": "https://t.me/Course_Number_1/9411",
    "Microscopy - Dr Izzy Jayasinghe": "https://t.me/Course_Number_1/9420",
    "Muscle Physiology - Prof. Jon Scott": "https://t.me/Course_Number_1/9427",
    "Natural Selection – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9440",
    "Natural Selection – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9447",
    "Plant Health and Disease – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9454",
    "Plant Health and Disease – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9457",
    "Plant Health and Disease – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9462",
    "Plant Structure and Function – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9465",
    "Plant Structure and Function – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9482",
    "Plant Structure and Function – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9501",
    "Quantitative Biology – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9514",
    "Quantitative Biology – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9519",
    "Quantitative Biology – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9524",
    "Sensory Systems - Prof. Jon Scott": "https://t.me/Course_Number_1/9529",
    "Smell - Prof. Matthew Cobb": "https://t.me/Course_Number_1/9540",
    "Stem Cells and Gene Editing - Dr James G. Smith": "https://t.me/Course_Number_1/9551",
    "Surface Anatomy - Prof. Claire Smith": "https://t.me/Course_Number_1/9564",
    "The Cardiovascular System - Ms Aarushi Agrawal": "https://t.me/Course_Number_1/9575",
    "The Eye - Dr Matthew Ivory": "https://t.me/Course_Number_1/9586",
    "The Eye and the Brain - Dr Daniel Baker": "https://t.me/Course_Number_1/9593",
    "The Genetic Age - Prof. Matthew Cobb": "https://t.me/Course_Number_1/9604",
    "The Human Immune System – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9617",
    "The Human Immune System – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9628",
    "The Human Immune System – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9639",
    "The Nervous System & The Brain – Edexcel GCSE (1BI0)_ Foundation Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9646",
    "The Nervous System & The Brain – Edexcel GCSE (1BI0)_ Higher Tier - Dr Matthew Ivory": "https://t.me/Course_Number_1/9655",
    "The Nervous System & The Brain – Edexcel GCSE (1SC0)_ Combined Science - Dr Matthew Ivory": "https://t.me/Course_Number_1/9666",
    "Virology - Dr Sarah Gretton": "https://t.me/Course_Number_1/9674",
    "Why Do We Age_ - Prof. Luana Maroja": "https://t.me/Course_Number_1/9685",
    "Advanced 3D Modeling with Catia _ Skillshare": "https://t.me/Course_Number_1/9703",
    "Foundational Math for Machine Learning _ LinkedIn": "https://t.me/Course_Number_1/9770",
    "Oncology _ Leukemia – White Blood Cell Pathology (WBC)": "https://t.me/Course_Number_1/9807",
    "Oncology _ Lung Cancer": "https://t.me/Course_Number_1/9818",
    "Oncology _ Lymphadenopathy – White Blood Cell Pathology (WBC)": "https://t.me/Course_Number_1/9827",
    "Oncology _ Neoplasms of the Endocrine System": "https://t.me/Course_Number_1/9844",
    "Oncology _ Neoplasms of the Gastrointestinal System": "https://t.me/Course_Number_1/9854",
    "Oncology _ Neoplasms of the Reproductive System": "https://t.me/Course_Number_1/9872",
    "Oncology _ Neoplastic Skin Diseases": "https://t.me/Course_Number_1/9902",
    "Oncology _ Principles of Neoplasia and Carcinogenesis": "https://t.me/Course_Number_1/9911",
    "Oncology _ Tumors of the CNS": "https://t.me/Course_Number_1/9939",
    "Histology - Human Organ Systems _ Cardiovascular Histology": "https://t.me/Course_Number_1/9948",
    "Histology - Human Organ Systems _ Endocrine Histology": "https://t.me/Course_Number_1/9967",
    "Histology - Human Organ Systems _ Gastrointestinal Histology": "https://t.me/Course_Number_1/9979",
    "Histology - Human Organ Systems _ Lymphoid Histology": "https://t.me/Course_Number_1/10013",
    "Histology - Human Organ Systems _ Reproductive Histology": "https://t.me/Course_Number_1/10022",
    "Histology - Human Organ Systems _ Respiratory Histology": "https://t.me/Course_Number_1/10052",
    "Histology - Human Organ Systems _ Sensory Histology": "https://t.me/Course_Number_1/10062",
    "Histology - Human Organ Systems _ Urinary Histology": "https://t.me/Course_Number_1/10080",
    "Histology - Types of Tissues _ Blood": "https://t.me/Course_Number_1/10089",
    "Histology - Types of Tissues _ Bone Marrow": "https://t.me/Course_Number_1/10096",
    "Histology - Types of Tissues _ Bone Tissue": "https://t.me/Course_Number_1/10103",
    "Histology - Types of Tissues _ Connective Tissue": "https://t.me/Course_Number_1/10114",
    "Histology - Types of Tissues _ Epithelial Tissue": "https://t.me/Course_Number_1/10127",
    "Histology - Types of Tissues _ Histological Techniques and Staining": "https://t.me/Course_Number_1/10145",
    "Histology - Types of Tissues _ Muscle Tissue": "https://t.me/Course_Number_1/10150",
    "Histology - Types of Tissues _ Nerve Tissue": "https://t.me/Course_Number_1/10157",
    "Histology - Types of Tissues _ The Mammalian Cell": "https://t.me/Course_Number_1/10177",
    "Immune System _ Adaptive Immune System": "https://t.me/Course_Number_1/10192",
    "Immune System _ Humoral Immunity and Cell-Mediated Immunity": "https://t.me/Course_Number_1/10224",
    "Immune System _ Hypersensitivity and Autoimmune Disease": "https://t.me/Course_Number_1/10238",
    "Immune System _ Overview and Cells": "https://t.me/Course_Number_1/10260",
    "Immune System _ Immunodeficiency and Immune Deficiency Diseases": "https://t.me/Course_Number_1/10269",
    "Immune System _ Immunodiagnostics": "https://t.me/Course_Number_1/10286",
    "Immune System _ Innate Immune System": "https://t.me/Course_Number_1/10295",
    "Immune System _ Transplantation Immunology": "https://t.me/Course_Number_1/10304",
    "Immune System _ Tumor Immunology": "https://t.me/Course_Number_1/10311",
    "Immune System _ Vaccine Immunology": "https://t.me/Course_Number_1/10319",
    "Visual Studio Code for C# Developers": "https://t.me/Course_Number_1/10335",
    "C# Basics For Absolute Beginners in C# and .NET": "https://t.me/Course_Number_1/10461",
    "C# Object-Oriented Programming for Beginners in C# and .NET": "https://t.me/Course_Number_1/10516",
    "Start Your Own Woodworking Business Today! _ udemy": "https://t.me/Course_Number_1/10629",



}


# ذخیره دیکشنری در یک فایل
with open('courses.pkl', 'wb') as f:
    pickle.dump(courses, f)
